'use client';
import Image from 'next/image';
import { useState, type ReactNode } from 'react';
import { Check, Coffee, Footprints, Zap, Car, TrainFront, Bus, Compass, ArrowUpRight, ArrowLeft, Pencil, Plus, Minus, ChevronDown, Sun, Sparkles, Users, CalendarDays, Heart } from 'lucide-react';
import { transports, currencies, months, tripDates, travellers, groupBudget, money, type Preferences, type Errors } from '@/lib/planner/model';
import { discoverySteps, moments, rhythms, reviewStep, journeyStory, discoveryErrors } from '@/lib/planner/discovery';
import TravelPostcard from './TravelPostcard';

type Props = {
  p: Preferences; step: number; furthest: number; editing: boolean; errors: Errors;
  update: <K extends keyof Preferences>(key: K, value: Preferences[K]) => void;
  go: (step: number) => void; next: () => void; generate: () => void;
  mode: string; saved: boolean; resume: () => void;
};
const titles = ['Which moments would you love?', 'How should your days feel?', 'When can we steal you away?', 'A little room for the good things.', 'Make yourself at home.', 'This is starting to feel like you.'];
const subtitles = [
  'A few things you love. A whole island to discover. Pick the moments you’d like more of.',
  'There’s no right way to do an island. Find a rhythm that feels like yours.',
  'A few days or a little longer. Let’s make room for your people and your plans.',
  'Give us a comfortable spending target. We’ll keep the unknowns clear along the way.',
  'Choose the kind of stay and journey you enjoy. We can help with the details.',
  'Your favourite moments, your people, your pace. Take one last look before we bring it together.',
];
const stayChoices = [
  { value: 'Boutique hotels', image: 'galle-lighthouse', title: 'A little character', note: 'Boutique hotels' },
  { value: 'Resorts', image: 'arugam-fishing-boats', title: 'Settle into a resort', note: 'Resorts' },
  { value: 'Guesthouses', image: 'market-life', title: 'A more local welcome', note: 'Guesthouses' },
  { value: 'Luxury hotels', image: 'negombo-sunset', title: 'A little indulgence', note: 'Luxury hotels' },
];
function Field({ label, name, error, children, hint }: { label: string; name: string; error?: string; children: ReactNode; hint?: string }) {
  return <div className="plan-field"><label htmlFor={name}>{label}</label>{children}{hint && <p className="field-hint">{hint}</p>}{error && <p className="field-error" id={`${name}-error`}>{error}</p>}</div>;
}
function Counter({ label, note, name, value, min, max, change, error }: { label: string; note?: string; name: string; value: number; min: number; max: number; change: (n: number) => void; error?: string }) {
  return <div className="traveller-counter"><div><label htmlFor={name}>{label}</label>{note && <small>{note}</small>}</div><div className="counter-controls"><button type="button" aria-label={`Fewer ${label.toLowerCase()}`} disabled={value <= min} onClick={() => change(value - 1)}><Minus size={16} /></button><input id={name} name={name} type="number" min={min} max={max} value={value} onChange={e => change(Math.min(max, Math.max(min, Number(e.target.value))))} aria-invalid={!!error} aria-describedby={error ? `${name}-error` : undefined} /><button type="button" aria-label={`More ${label.toLowerCase()}`} disabled={value >= max} onClick={() => change(value + 1)}><Plus size={16} /></button></div>{error && <p id={`${name}-error`} className="field-error">{error}</p>}</div>;
}
export default function PlanningForm({ p, step, furthest, editing, errors, update, go, next, generate, mode, saved, resume }: Props) {
  const [showAll, setShowAll] = useState(false);
  const shownMoments = moments.filter((m, i) => showAll || i < 6 || p.interests.includes(m.name));
  function toggleMoment(name: string) {
    const removing = p.interests.includes(name);
    update('interests', removing ? p.interests.filter(i => i !== name) : [...p.interests, name]);
    // Collapsed extra cards disappear when deselected; keep keyboard focus in the chooser.
    if (removing && !showAll && moments.findIndex(m => m.name === name) >= 6) {
      requestAnimationFrame(() => document.getElementById('more-moments')?.focus());
    }
  }
  const story = journeyStory(p);
  const validDates = !Object.keys(discoveryErrors(p, 2)).some(k => ['arrivalDate', 'departureDate', 'duration', 'month'].includes(k));
  const validBudget = p.budget && !discoveryErrors(p, 3).budget;
  const props = (name: keyof Preferences) => ({ id: name, name, 'aria-invalid': !!errors[name], 'aria-describedby': errors[name] ? `${name}-error` : undefined });
  const text = (name: 'arrivalDate' | 'departureDate', label: string, type = 'text', hint?: string) => <Field key={name} name={name} label={label} error={errors[name]} hint={hint}><input {...props(name)} type={type} value={p[name]} onChange={e => update(name, e.target.value)} maxLength={160} {...(type === 'date' ? { min: new Date().toISOString().slice(0, 10) } : {})} /></Field>;
  const nextLabel = editing ? 'Save & return to my journey' : ['Find my rhythm', 'Make room for the trip', 'Set my budget', 'Find my comforts', 'See my journey'][step];
  return <div className={`discovery-layout discovery-step-${step}`}>
    <div className="discovery-sidebar"><TravelPostcard p={p} /></div>
    <section className="discovery-content" aria-labelledby="step-heading">
      <nav className="discovery-progress" aria-label="Planning progress"><ol>{discoverySteps.map((name, i) => <li key={name} className={step === i ? 'current' : furthest > i ? 'complete' : ''}><button type="button" disabled={i > furthest} aria-current={step === i ? 'step' : undefined} aria-label={`${name}, step ${i + 1} of ${discoverySteps.length}`} onClick={() => go(i)}><span>{furthest > i && step !== i ? <Check size={12} /> : `0${i + 1}`}</span><b>{name.replace('Your ', '')}</b></button></li>)}</ol><div><span>{step === 0 ? 'A FEW CHOICES. A THOUSAND POSSIBILITIES.' : discoverySteps[step]}</span><span>{step + 1} / {discoverySteps.length}</span></div></nav>
      <div className="step-intro discovery-intro"><p className="eyebrow">{['LET’S MAKE SRI LANKA YOURS', 'LESS RUSH. MORE YOU.', 'GOOD DAYS. GOOD COMPANY.', 'YOUR COMFORT ZONE', 'THE WAY YOU LIKE TO TRAVEL', 'YOUR NEXT CHAPTER'][step]}</p><h1 id="step-heading" tabIndex={-1}>{titles[step]}</h1><p>{subtitles[step]}</p></div>
      <form noValidate onSubmit={e => { e.preventDefault(); if (step === reviewStep) generate(); else next(); }}>
        <div className="discovery-fields" key={step}>
        {!!Object.keys(errors).length && <div className="plan-error" role="alert"><strong>A little more detail, please.</strong><ul>{Object.entries(errors).map(([key, message]) => <li key={key}><a href={`#${key}`}>{message}</a></li>)}</ul></div>}
        {step === 0 && <div className="moments-section"><fieldset className="interest-photo-fieldset" id="interests" aria-describedby={errors.interests ? 'interests-error' : 'moments-hint'}><legend className="sr-only">Choose your interests</legend><div className="moment-grid">{shownMoments.map(m => <label className={`moment-card ${p.interests.includes(m.name) ? 'selected' : ''}`} key={m.name}><input type="checkbox" aria-label={m.name} aria-invalid={!!errors.interests} checked={p.interests.includes(m.name)} onChange={() => toggleMoment(m.name)} /><Image src={`/images/${m.image}.webp`} alt="" fill sizes="(max-width: 760px) 44vw, (max-width: 1200px) 24vw, 17vw" /><span className="moment-shade" /><span className="selection-mark">{p.interests.includes(m.name) ? <Check size={14} /> : <Plus size={14} />}</span><span className="moment-caption"><small>{m.name}</small><strong>{m.title}</strong><span>{m.note}</span></span></label>)}</div></fieldset><div className="moment-tools"><p id="moments-hint" aria-live="polite">{p.interests.length ? `${p.interests.length} moments for your kind of island.` : 'Pick as many as you like.'}</p><button type="button" className="plan-text" id="more-moments" aria-expanded={showAll} onClick={() => setShowAll(v => !v)}>{showAll ? 'A little less' : 'More ways to explore'}<ChevronDown size={15} className={showAll ? 'turned' : ''} /></button></div>{errors.interests && <p id="interests-error" className="field-error">{errors.interests}</p>}</div>}
        {step === 1 && <fieldset className="choice-fieldset" id="pace"><legend className="sr-only">Your travel pace</legend><div className="rhythm-choices">{rhythms.map((rhythm, i) => { const Icon = [Coffee, Footprints, Zap][i]; return <label key={rhythm.value} className={`rhythm-card ${p.pace === rhythm.value ? 'selected' : ''}`}><input type="radio" name="pace" aria-label={rhythm.value} checked={p.pace === rhythm.value} onChange={() => update('pace', rhythm.value)} /><div className="rhythm-heading"><Icon size={24} strokeWidth={1.4} /><div><strong>{rhythm.title}</strong><small>{rhythm.value} pace · {rhythm.note}</small></div><span className="rhythm-check">{p.pace === rhythm.value && <Check size={14} />}</span></div><div className="rhythm-day">{rhythm.beats.map((beat, j) => <span key={beat}><i>{['AM', 'MIDDAY', 'PM'][j]}</i>{beat}</span>)}</div></label>; })}</div><p className="discovery-aside-note"><Sun size={15} /> A feel for the rhythm, not your final day-by-day plan.</p></fieldset>}
        {step === 2 && <div className="question-stack">
          <fieldset className="choice-fieldset"><legend className="sr-only">Your dates</legend><div className="date-choice-row"><label className={!p.undecided ? 'selected' : ''}><input type="radio" name="dateMode" checked={!p.undecided} onChange={() => update('undecided', false)} /><CalendarDays size={18} /> I have dates in mind{!p.undecided && <Check size={14} />}</label><label className={p.undecided ? 'selected' : ''}><input type="radio" name="dateMode" checked={p.undecided} onChange={() => update('undecided', true)} /><Sun size={18} /> I’m still dreaming{p.undecided && <Check size={14} />}</label></div></fieldset>
          {p.undecided ? <><div className="duration-picks" aria-label="Trip duration suggestions">{[5, 7, 10, 14, 21].map(n => <button type="button" key={n} aria-pressed={p.duration === n} onClick={() => update('duration', n)}>{n}<small>days</small></button>)}</div><div className="field-grid"><Field name="duration" label="How many days?" error={errors.duration} hint="Choose 1–21 days, including travel days."><input {...props('duration')} type="number" min={1} max={21} value={p.duration || ''} onChange={e => update('duration', Number(e.target.value))} /></Field><Field name="month" label="Preferred month" error={errors.month}><select {...props('month')} value={p.month} onChange={e => update('month', e.target.value)}>{months.map(m => <option key={m}>{m}</option>)}</select></Field></div></> : <><div className="field-grid">{text('arrivalDate', 'Arrival date', 'date')}{text('departureDate', 'Departure date', 'date')}</div>{errors.duration && <p id="duration-error" className="field-error">{errors.duration}</p>}</>}
          <div className="question-divider" /><div className="question-heading"><Users size={19} /><h2 className="question-title">Who’s coming along?</h2></div><div className="traveller-counters"><Counter name="adults" label="Adults" note="18 and over" min={1} max={12} value={p.adults} change={v => update('adults', v)} error={errors.adults} /><Counter name="children" label="Children" note="Little explorers, 0–17" min={0} max={8} value={p.children} change={v => update('children', v)} error={errors.children} /></div>
          {p.children > 0 && <fieldset className="ages-fields" id="ages"><legend>How old will the little explorers be?</legend><div className="field-grid">{p.ages.map((age, i) => <Field key={i} name={`age-${i}`} label={`Child ${i + 1}`}><input id={`age-${i}`} aria-invalid={!!errors.ages} aria-describedby={errors.ages ? 'ages-error' : undefined} type="number" min={0} max={17} value={age} onChange={e => update('ages', p.ages.map((v, j) => i === j ? e.target.value : v))} /></Field>)}</div>{errors.ages && <p id="ages-error" className="field-error">{errors.ages}</p>}</fieldset>}
        </div>}
        {step === 3 && <div className="question-stack budget-chapter"><div className="budget-invitation"><span><Sun size={26} strokeWidth={1.3} /></span><p>For the stays, the journeys,<br /><strong>and the moments in between.</strong></p></div><div className="field-grid budget-grid"><Field name="budget" label="Budget amount (optional)" error={errors.budget}><input {...props('budget')} inputMode="decimal" type="text" placeholder="Your comfortable amount" value={p.budget} maxLength={12} onChange={e => update('budget', e.target.value)} /></Field><Field name="currency" label="Currency" error={errors.currency}><select {...props('currency')} value={p.currency} onChange={e => update('currency', e.target.value)}>{currencies.map(c => <option key={c}>{c}</option>)}</select></Field></div><fieldset className="choice-fieldset"><legend>Who does that cover?</legend><div className="budget-basis">{[['group', 'The whole group', 'One budget, all your people'], ['person', 'Each person', 'The same target per traveller']].map(([value, label, hint]) => <label className={p.budgetBasis === value ? 'selected' : ''} key={value}><input type="radio" name="budgetBasis" checked={p.budgetBasis === value} onChange={() => update('budgetBasis', value as Preferences['budgetBasis'])} /><span><strong>{label}</strong><small>{hint}</small></span></label>)}</div></fieldset>{p.budgetBasis === 'person' && <p className="field-hint">Applies to every traveller, including children.{validBudget ? ` Your group target: ${money(groupBudget(p)!, p.currency)}.` : ''}</p>}<label className="check-row"><input type="checkbox" checked={p.flightsIncluded} onChange={e => update('flightsIncluded', e.target.checked)} /> My budget includes international flights</label>{p.flightsIncluded && <p className="field-hint">Flight prices remain unknown without a date-specific quote. We won’t assume the whole budget is available for Sri Lanka.</p>}<div className="budget-reassurance"><Compass size={20} /><div><strong>Still finding your comfort zone?</strong><p>Leave the amount empty and we’ll help you explore. Every price we can’t confirm will be clearly marked.</p>{p.budget && <button className="plan-text" type="button" onClick={() => update('budget', '')}>Help me decide instead</button>}</div></div></div>}
        {step === 4 && <div className="question-stack"><fieldset className="choice-fieldset" id="accommodation"><legend>Where would you like to settle in?</legend><div className="stay-photo-grid">{stayChoices.map(stay => <label className={`stay-photo-card ${p.accommodation === stay.value ? 'selected' : ''}`} key={stay.value}><input type="radio" name="accommodation" aria-label={stay.value} checked={p.accommodation === stay.value} onChange={() => update('accommodation', stay.value)} /><Image src={`/images/${stay.image}.webp`} alt="" fill sizes="(max-width: 760px) 44vw, 25vw" /><span className="moment-shade" /><span className="selection-mark">{p.accommodation === stay.value && <Check size={14} />}</span><span className="moment-caption"><small>{stay.title}</small><strong>{stay.value}</strong></span></label>)}</div><label className={`help-choice ${p.accommodation === 'Help me decide' ? 'selected' : ''}`}><input type="radio" name="accommodation" checked={p.accommodation === 'Help me decide'} onChange={() => update('accommodation', 'Help me decide')} /><Compass size={18} /><span>Help me find my kind of stay</span></label><p className="field-hint">Island imagery for inspiration. Specific properties come with your itinerary.</p></fieldset><fieldset className="choice-fieldset" id="transport"><legend>And between the moments?</legend><div className="transport-grid">{transports.map((value, i) => { const Icon = [Compass, Car, TrainFront, Bus, Car][i]; return <label className={`transport-choice ${p.transport === value ? 'selected' : ''}`} key={value}><input type="radio" name="transport" checked={p.transport === value} onChange={() => update('transport', value)} /><Icon size={19} /><span>{value}</span>{p.transport === value && <Check size={14} />}</label>; })}</div></fieldset><details className="discovery-details" open={p.mustVisit || p.accessibility || errors.mustVisit || errors.accessibility ? true : undefined}><summary><span>A few personal touches<small>Must-visits, access needs & anything to plan around</small></span><Plus size={17} /></summary><div className="details-fields"><Field name="mustVisit" label="Anywhere you simply can’t miss? (optional)" error={errors.mustVisit}><textarea {...props('mustVisit')} maxLength={600} rows={2} placeholder="A sunrise in Ella, a few days in Galle…" value={p.mustVisit} onChange={e => update('mustVisit', e.target.value)} /></Field><Field name="accessibility" label="Anything we should plan around? (optional)" hint="Step-free access, walking limits, dietary needs… Please leave out personal contact or medical details." error={errors.accessibility}><textarea {...props('accessibility')} maxLength={600} rows={2} value={p.accessibility} onChange={e => update('accessibility', e.target.value)} /></Field></div></details></div>}
        {step === reviewStep && <div className="review-stack"><div className="journey-brief"><div className="brief-photos" aria-hidden="true">{(p.interests.length ? p.interests.slice(0, 3).map(i => moments.find(m => m.name === i)!) : moments.slice(0, 3)).filter(Boolean).map(m => <div key={m.name}><Image src={`/images/${m.image}.webp`} alt="" fill sizes="(max-width: 760px) 30vw, 20vw" /></div>)}<span><Heart size={16} /> MADE OF YOUR FAVOURITE THINGS</span></div><div className="brief-copy"><p>{story.duration || 'A little time away'} for {p.adults + p.children}.</p><h2>{story.title}</h2><p>{story.description}</p></div></div><ReviewBlock title="Your moments & rhythm" edit={() => go(0)}><div className="review-tags">{p.interests.map(i => <span key={i}>{i}</span>)}</div><p>{p.pace} pace <button className="inline-edit" type="button" onClick={() => go(1)}>Change rhythm</button></p></ReviewBlock><ReviewBlock title="Your time & people" edit={() => go(2)}><strong>{validDates ? tripDates(p) : 'Dates to confirm'}</strong><p>{travellers(p)}{p.children > 0 ? ` · Ages ${p.ages.join(', ')}` : ''}</p><p>Arrive: {p.arrival}{p.arrivalTime ? ` · ${p.arrivalTime}` : ''}<br />Depart: {p.departure}{p.departureTime ? ` · ${p.departureTime}` : ''}</p></ReviewBlock><ReviewBlock title="Your budget" edit={() => go(3)}><p>{validBudget ? `${money(Number(p.budget), p.currency)} ${p.budgetBasis === 'person' ? 'per person' : 'for the group'}` : 'Help me decide'}</p><p>{p.flightsIncluded ? 'Includes' : 'Excludes'} international flights</p></ReviewBlock><ReviewBlock title="Your comforts" edit={() => go(4)}><p>{p.accommodation} · {p.transport}</p>{p.mustVisit && <p><strong>Must-visits:</strong> {p.mustVisit}</p>}{p.accessibility && <p><strong>Plan around:</strong> {p.accessibility}</p>}</ReviewBlock><div className="review-note"><Sparkles size={20} /><p>{mode === 'sample' ? 'You’ll receive a clearly labelled sample. Routes, special requirements, prices and availability are not live-verified.' : mode === 'live' ? 'We’ll research your journey using these preferences. Your answers are sent to our AI provider; prices and availability may need confirmation.' : 'The planning service needs to connect before we can build your journey.'} Your completed itinerary is read-only.</p></div></div>}
        </div>
        <div className="form-actions discovery-actions">{step > 0 ? <button className="plan-back" type="button" onClick={() => go(editing ? reviewStep : step - 1)}><ArrowLeft size={17} />{editing ? 'Back to my journey' : 'Back'}</button> : <span className="first-step-note"><Check size={14} /> No account. Just you.</span>}<button className="plan-primary" type="submit" disabled={step === reviewStep && mode === 'checking'}>{step === reviewStep ? 'Create my itinerary' : nextLabel}<ArrowUpRight size={19} /></button></div>
      </form>
      <p className="form-footnote">Your progress is saved on this device. Pick up where you left off.</p>
      {step === 0 && saved && <button className="saved-journey-link plan-text" type="button" onClick={resume}>Return to your saved itinerary <ArrowUpRight size={15} /></button>}
    </section>
  </div>;
}
function ReviewBlock({ title, edit, children }: { title: string; edit: () => void; children: ReactNode }) { return <section className="review-block"><div><h2>{title}</h2><button type="button" onClick={edit} aria-label={`Edit ${title.toLowerCase()}`}><Pencil size={14} /> Edit</button></div><div className="review-body">{children}</div></section>; }
