import type { Author, CommunityComment, CommunityPost } from './model';
import photos from './photos.json';

// Illustrative editorial content. These are fictional profiles, not real members or testimonials.
export const authors: Author[] = [
  { id: 'maya', name: 'Maya Bennett', initials: 'MB', color: 'clay', country: 'United Kingdom', bio: 'Window seats, slow mornings, and taking the scenic route. Usually looking for a good cup of tea.' },
  { id: 'leo', name: 'Leo Martin', initials: 'LM', color: 'ocean', country: 'France', bio: 'One more wave, one more day. Exploring the island with a board and a very loose plan.' },
  { id: 'anika', name: 'Anika Perera', initials: 'AP', color: 'jungle', country: 'Sri Lanka', bio: 'Finding something new in the place I call home. Food, little streets, and stories worth sharing.' },
  { id: 'noah', name: 'Noah Kim', initials: 'NK', color: 'gold', country: 'Australia', bio: 'Early starts, wild places, and a camera that always comes along.' },
  { id: 'sofia', name: 'Sofia Rossi', initials: 'SR', color: 'plum', country: 'Italy', bio: 'Travelling slowly enough to notice the small things. Currently collecting sunsets.' },
];

// All supplied images appear once in the memory feed. Photo credits identify the photographers;
// the traveller profiles and accompanying captions are illustrative, not photographer testimonials.
export const seedPosts: CommunityPost[] = [
  { id: "long-way-to-ella", authorId: "maya", kind: "story", title: "The best part wasn’t getting there.", body: "The curve of the tracks. An open window. A landscape that makes you forget to check the time. Some journeys stay with you long after you arrive.", destination: "Sri Lanka", topic: "Slow", createdAt: "2026-09-22T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[6], original: "/images/community/matt-dany-ePAa2c9XbtE-unsplash.jpg", alt: "A blue passenger train curving through green hills, with travellers looking out of its windows", credit: "Matt Dany" }] },
  { id: "a-view-for-two", authorId: "sofia", kind: "moment", title: "Some views are better shared.", body: "Two people, a little patch of rock, and a whole world of green. The kind of quiet you wish you could bring home.", destination: "Sri Lanka", topic: "Slow", createdAt: "2026-09-21T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[5], original: "/images/community/lou-lou-b-photo-xSI-8hwyUzE-unsplash.jpg", alt: "Two travellers sitting together on a rock overlooking a forest and a distant rock formation", credit: "Lou Lou B Photo" }] },
  { id: "one-more-wave", authorId: "leo", kind: "moment", title: "Just one more wave. Always one more.", body: "Salt on your skin. The last of the light. That feeling of having nowhere else you need to be.", destination: "Sri Lanka", topic: "Coastal", createdAt: "2026-09-20T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[19], original: "/images/community/zoshua-colah-PY_wDYTDvRw-unsplash.jpg", alt: "Surfers riding a small wave beside a palm-lined coast at sunset", credit: "Zoshua Colah" }] },
  { id: "window-seat-dreams", authorId: "maya", kind: "question", title: "Which journey would you take again?", body: "Sometimes the memory is everything between two places. A window seat, passing rooftops, the hills opening up. Which journey stayed with you?", destination: "Sri Lanka", topic: "Slow", createdAt: "2026-09-19T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[0], original: "/images/community/anton-lecock-TPtaNsBOW9Q-unsplash.jpg", alt: "A blue train winding through a hillside town beneath dark clouds", credit: "Anton Lecock" }] },
  { id: "steps-into-stillness", authorId: "sofia", kind: "story", title: "A few steps into stillness.", body: "The afternoon softens. Footsteps slow. There are places that invite you to put the camera down for a moment and simply take it all in.", destination: "Sri Lanka", topic: "Timeless", createdAt: "2026-09-18T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[7], original: "/images/community/morgan-nott-ZnNNSp6Oe90-unsplash.jpg", alt: "A visitor walking up steps towards a large white seated Buddha statue", credit: "Morgan Nott" }] },
  { id: "tea-country-voices", authorId: "anika", kind: "moment", title: "The people are part of the place.", body: "A landscape becomes a memory through the people in it. The everyday moments deserve a place in the album, too.", destination: "Sri Lanka", topic: "Slow", createdAt: "2026-09-17T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[11], original: "/images/community/praveen-maleesha-gCjCxFUugoQ-unsplash.jpg", alt: "Tea workers standing together among bright green tea bushes", credit: "Praveen Maleesha" }] },
  { id: "a-little-perspective", authorId: "noah", kind: "moment", title: "A little room to breathe.", body: "Nothing to tick off. Nothing to hurry towards. Just a mountain view and the luxury of staying a little longer.", destination: "Sri Lanka", topic: "Wild", createdAt: "2026-09-16T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[4], original: "/images/community/kirsty-barnby-JbZG7U093Bw-unsplash.jpg", alt: "A traveller sitting on a rock overlooking a wide green mountain valley", credit: "Kirsty Barnby" }] },
  { id: "between-the-plans", authorId: "sofia", kind: "moment", title: "The moments between the plans.", body: "The waiting, the laughing, the ordinary little pauses. Somehow these become the photographs you keep coming back to.", destination: "Sri Lanka", topic: "Slow", createdAt: "2026-09-15T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[8], original: "/images/community/pasha-chusovitin-YQBx0g21iz8-unsplash.jpg", alt: "Two travellers standing beside a roadside barrier in bright sunshine", credit: "Pasha Chusovitin" }] },
  { id: "wild-quiet", authorId: "noah", kind: "story", title: "And then everyone went quiet.", body: "An elephant crossing an open landscape. A vehicle paused in the distance. Some encounters are a reminder to slow down and let the wild set the pace.", destination: "Sri Lanka", topic: "Wild", createdAt: "2026-09-14T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[16], original: "/images/community/tom-paisley-v2zEiziFb44-unsplash.jpg", alt: "An elephant in open grassland with a safari vehicle in the background", credit: "Tom Paisley" }] },
  { id: "a-table-in-the-shade", authorId: "anika", kind: "question", title: "Where did you lose track of time?", body: "A table in the shade, a long conversation, and no reason to leave just yet. Tell us about the little place you are still thinking about.", destination: "Sri Lanka", topic: "Flavourful", createdAt: "2026-09-13T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[9], original: "/images/community/petr-sevcovic-cBX6hBxRptY-unsplash.jpg", alt: "Travellers gathered around outdoor café tables beneath palm trees", credit: "Petr Sevcovic" }] },
  { id: "waterfall-afternoon", authorId: "noah", kind: "moment", title: "Let the whole world rush past.", body: "A waterfall fills the frame. For a moment, everything else feels wonderfully small.", destination: "Sri Lanka", topic: "Wild", createdAt: "2026-09-12T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[17], original: "/images/community/tomas-malik-TW_euWsc-Ds-unsplash.jpg", alt: "A person standing near the base of a broad waterfall cascading over dark rock", credit: "Tomas Malik" }] },
  { id: "one-more-little-street", authorId: "anika", kind: "story", title: "One archway. Another beginning.", body: "Follow the light through an old doorway. Let one street lead to another. A little curiosity can be the best thing you bring along.", destination: "Sri Lanka", topic: "Timeless", createdAt: "2026-09-11T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[10], original: "/images/community/praveen-maleesha-5XSOMBEhJWQ-unsplash.jpg", alt: "Visitors walking beneath an old stone archway into the daylight", credit: "Praveen Maleesha" }] },
  { id: "roads-worth-remembering", authorId: "maya", kind: "moment", title: "Take the road that makes you pause.", body: "A roadside tree. A splash of green. A small moment that would never have made it onto an itinerary.", destination: "Sri Lanka", topic: "Slow", createdAt: "2026-09-10T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[12], original: "/images/community/raissa-lara-lutolf-fasel-FpCrOqzK3JQ-unsplash.jpg", alt: "A green tuk-tuk and travellers beside a tall tree on a quiet hillside road", credit: "Raissa Lara Lütolf-Fasel" }] },
  { id: "when-the-island-glows", authorId: "anika", kind: "moment", title: "Stay until the colours change.", body: "The sky turns violet, then rose. Branches hold the last of the evening. Some memories arrive when the day is almost over.", destination: "Sri Lanka", topic: "Timeless", createdAt: "2026-09-09T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[1], original: "/images/community/chathura-anuradha-subasinghe-WsNp3rxrK-M-unsplash.jpg", alt: "An illuminated white stupa framed by trees beneath a pink and purple twilight sky", credit: "Chathura Anuradha Subasinghe" }] },
  { id: "above-the-everyday", authorId: "noah", kind: "moment", title: "A view bigger than the day.", body: "A quiet seat above the trees. Mist between the hills. A reminder that the best plans leave room for a pause.", destination: "Sri Lanka", topic: "Wild", createdAt: "2026-09-08T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[13], original: "/images/community/sander-traa-CXMfimT0pAE-unsplash.jpg", alt: "A traveller sitting on a stone ledge overlooking misty green hills", credit: "Sander Traa" }] },
  { id: "gentle-moments", authorId: "anika", kind: "moment", title: "A small moment of tenderness.", body: "A photograph can hold so many details: a gesture, a little movement, the life unfolding around it. Take a second look.", destination: "Sri Lanka", topic: "Wild", createdAt: "2026-09-07T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[18], original: "/images/community/wietse-jongsma-H-FTkkOdBgo-unsplash.jpg", alt: "An adult elephant and a calf beside a person in a palm-dotted field", credit: "Wietse Jongsma" }] },
  { id: "a-trail-of-your-own", authorId: "noah", kind: "story", title: "A little further. A little freer.", body: "Boots on the trail, the valley below, and a sky that keeps changing. Some days remind you how good it feels to be outside.", destination: "Sri Lanka", topic: "Wild", createdAt: "2026-09-06T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[14], original: "/images/community/simmel-f7SSF9ECUR8-unsplash.jpg", alt: "A hiker with a backpack standing on a rocky mountain trail beneath a dramatic sky", credit: "Simmel" }] },
  { id: "light-and-living-tradition", authorId: "sofia", kind: "moment", title: "An evening you can still feel.", body: "Warm light. Movement. A moment full of energy. The memories that stay with us are not always the quiet ones.", destination: "Sri Lanka", topic: "Timeless", createdAt: "2026-09-05T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[15], original: "/images/community/thilina-alagiyawanna-k76cGnRciZo-unsplash.jpg", alt: "People taking part in a traditional performance illuminated by bright flames", credit: "Thilina Alagiyawanna" }] },
  { id: "the-unhurried-way", authorId: "leo", kind: "moment", title: "The unhurried way around.", body: "Two wheels, a leafy path, a little curiosity. Sometimes a good day needs very little else.", destination: "Sri Lanka", topic: "Slow", createdAt: "2026-09-04T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[3], original: "/images/community/isuru-ranasinha-X6WqnHHCCQA-unsplash.jpg", alt: "A cyclist with a pink basket riding beside dense tropical greenery", credit: "Isuru Ranasinha" }] },
  { id: "the-view-from-here", authorId: "maya", kind: "moment", title: "Wish you could bottle this feeling.", body: "A glimpse of moving water, green hills, and the shoes that brought you here. A tiny piece of a much bigger journey.", destination: "Sri Lanka", topic: "Wild", createdAt: "2026-09-03T10:00:00Z", visited: "A memory from the island", likes: 0, sample: true, photos: [{ ...photos[2], original: "/images/community/eddy-billard--k480xJCWvM-unsplash.jpg", alt: "A seated traveller’s shoes above a waterfall and a green valley", credit: "Eddy Billard" }] },
];
export const seedComments: CommunityComment[] = [
  { id: 'c1', postId: 'long-way-to-ella', name: 'Sofia Rossi', body: 'The window-seat memories are always my favourites. Such a lovely reminder to slow down.', sample: true },
];
