/* eslint-disable @typescript-eslint/no-require-imports -- Node CommonJS test runner. */
/* Browser integration checks. Set PLAYWRIGHT_MODULE if Playwright is installed outside this repo. */
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:3001';
const output = process.env.TEST_ARTIFACTS || '/private/tmp/hellosrilanka-planner-review';
(async () => {
  await fs.mkdir(output, { recursive: true });
  const browser = await chromium.launch({ headless: true, executablePath: process.env.TEST_BROWSER_PATH });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', async r => { if (r.url().includes('/api/itinerary') && r.status() >= 400) console.error('API', r.status(), await r.text()); });
  try {
    await page.goto(base + '/');
    await page.locator('.nav-cta').click();
    await page.getByRole('button', { name: 'Find my rhythm', exact: true }).waitFor();
    await page.screenshot({ path: output + '/moments-desktop.png', fullPage: true });
    assert.equal(await page.locator('.moment-card').count(), 6);
    await page.getByRole('button', { name: 'Find my rhythm', exact: true }).click();
    assert.ok(await page.getByRole('alert').count(), 'An interest is required before moving on');
    await page.getByRole('checkbox', { name: 'Nature', exact: true }).check();
    await page.getByRole('checkbox', { name: 'Food', exact: true }).check();
    assert.match(await page.locator('.postcard-copy h2').innerText(), /Green escapes.*Local flavours/is);
    await page.getByRole('button', { name: 'More ways to explore', exact: true }).click();
    assert.equal(await page.locator('.moment-card').count(), 10);
    await page.getByRole('checkbox', { name: 'Wellness', exact: true }).check();
    await page.getByRole('button', { name: 'A little less', exact: true }).click();
    assert.ok(await page.getByRole('checkbox', { name: 'Wellness', exact: true }).isVisible(), 'Extra selected moments remain visible');
    await page.getByRole('checkbox', { name: 'Wellness', exact: true }).click();
    assert.equal(await page.getByRole('checkbox', { name: 'Wellness', exact: true }).count(), 0);
    await page.screenshot({ path: output + '/postcard-desktop.png', fullPage: true });
    await page.getByRole('button', { name: 'Find my rhythm', exact: true }).click();
    await page.getByRole('radio', { name: 'Relaxed', exact: true }).check();
    assert.match(await page.locator('.rhythm-card.selected').innerText(), /A slow breakfast/);
    assert.match(await page.locator('.postcard-copy').innerText(), /Room to slow down/);
    await page.screenshot({ path: output + '/rhythm-desktop.png', fullPage: true });
    await page.getByRole('button', { name: 'Make room for the trip', exact: true }).click();
    await page.getByRole('button', { name: 'Set my budget', exact: true }).click();
    assert.ok(await page.getByRole('alert').count(), 'Missing dates show validation');
    await page.getByRole('radio', { name: 'I’m still dreaming', exact: true }).check();
    await page.getByLabel('How many days?').fill('7');
    await page.getByLabel('Preferred month').selectOption('February');
    await page.getByRole('button', { name: 'More children', exact: true }).click();
    await page.getByLabel('Child 1', { exact: true }).fill('8');
    assert.equal(await page.locator('.discovery-details').getAttribute('open'), null, 'Flight details start collapsed');
    await page.reload();
    assert.equal(await page.getByLabel('Child 1', { exact: true }).inputValue(), '8');
    await page.getByRole('button', { name: 'Set my budget', exact: true }).click();
    await page.getByLabel('Budget amount (optional)', { exact: true }).fill('1500');
    await page.getByRole('radio', { name: /Each person/ }).check();
    await page.screenshot({ path: output + '/budget-desktop.png', fullPage: true });
    await page.getByRole('button', { name: 'Find my comforts', exact: true }).click();
    await page.getByRole('radio', { name: 'Boutique hotels', exact: true }).check();
    await page.getByLabel('Train & driver', { exact: true }).check();
    await page.screenshot({ path: output + '/comforts-desktop.png', fullPage: true });
    await page.getByRole('button', { name: 'See my journey', exact: true }).click();
    assert.match(await page.locator('.review-stack').innerText(), /per person/);
    assert.match(await page.locator('.journey-brief').innerText(), /7 days for 3/);
    await page.getByRole('button', { name: 'Edit your time & people', exact: true }).click();
    assert.equal(await page.getByLabel('How many days?').inputValue(), '7');
    await page.getByRole('button', { name: 'Save & return to my journey', exact: true }).click();
    await page.getByRole('button', { name: 'Create my itinerary', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Change rhythm', exact: true }).click();
    await page.getByRole('radio', { name: 'Balanced', exact: true }).check();
    await page.reload();
    await page.getByRole('button', { name: 'Save & return to my journey', exact: true }).click();
    await page.screenshot({ path: output + '/review-desktop.png', fullPage: true });
    await page.getByRole('button', { name: 'Create my itinerary', exact: true }).click();
    await page.locator('#result-heading').waitFor();
    assert.equal(await page.locator('.day-card').count(), 7);
    assert.equal(await page.locator('.day-toggle').first().getAttribute('aria-expanded'), 'true');
    await page.locator('.day-toggle').nth(1).click();
    assert.equal(await page.locator('.day-toggle').nth(1).getAttribute('aria-expanded'), 'true');
    await page.locator('.day-toggle').nth(1).click();
    assert.equal(await page.locator('.day-toggle').nth(1).getAttribute('aria-expanded'), 'false');
    assert.equal(await page.getByRole('button', { name: 'Map', exact: true }).count(), 0);
    await page.screenshot({ path: output + '/itinerary-desktop.png', fullPage: true });
    await page.reload(); await page.locator('#result-heading').waitFor();
    assert.equal(await page.locator('.day-card').count(), 7);
    await page.getByRole('button', { name: 'Download as image', exact: true }).click();
    await page.locator('.export-previews figure').first().waitFor();
    assert.ok(await page.locator('.export-previews figure').count() >= 1, 'Overview renders');
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('link', { name: 'Download PNG', exact: true }).first().click();
    const download = await downloadPromise; await download.saveAs(output + '/overview.png');
    const png = await fs.readFile(output + '/overview.png');
    assert.equal(png.readUInt32BE(16), 1440); assert.equal(png.readUInt32BE(20), 1920);
    await page.getByLabel('Choose your image').selectOption('2');
    await page.locator('.export-previews figure').first().waitFor();
    await page.getByLabel('Include estimated costs').uncheck();
    await page.locator('.export-previews figure').first().waitFor();
    const dayPromise = page.waitForEvent('download');
    await page.getByRole('link', { name: 'Download PNG', exact: true }).first().click();
    await (await dayPromise).saveAs(output + '/day-2.png');
    await page.screenshot({ path: output + '/export-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: output + '/export-mobile.png', fullPage: true });
    await page.getByRole('button', { name: 'Back to itinerary', exact: true }).click();
    await page.screenshot({ path: output + '/itinerary-mobile.png', fullPage: true });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No result overflow');
    await page.getByRole('button', { name: 'Start a new trip', exact: true }).click();
    await page.screenshot({ path: output + '/moments-mobile.png', fullPage: true });
    await page.getByRole('checkbox', { name: 'Nature', exact: true }).check();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No form overflow');
    await page.getByRole('button', { name: 'Find my rhythm', exact: true }).click();
    await page.screenshot({ path: output + '/rhythm-mobile.png', fullPage: true });
    await page.getByRole('button', { name: 'Make room for the trip', exact: true }).click();
    await page.getByRole('radio', { name: 'I’m still dreaming', exact: true }).check();
    await page.screenshot({ path: output + '/time-mobile.png', fullPage: true });
    await page.getByRole('button', { name: 'Set my budget', exact: true }).click();
    await page.screenshot({ path: output + '/budget-mobile.png', fullPage: true });
    await page.getByRole('button', { name: 'Find my comforts', exact: true }).click();
    await page.screenshot({ path: output + '/comforts-mobile.png', fullPage: true });
    await page.getByRole('button', { name: 'See my journey', exact: true }).click();
    await page.screenshot({ path: output + '/review-mobile.png', fullPage: true });
    // Simulate a disconnected stream. The retry must reuse the request id.
    let firstId;
    await page.route('**/api/itinerary', async route => {
      if (route.request().method() !== 'POST') return route.continue();
      firstId = route.request().postDataJSON().id;
      await route.fulfill({ contentType: 'application/x-ndjson', body: '{"stage":"Researching destinations"}\n' });
    });
    await page.getByRole('button', { name: 'Create my itinerary', exact: true }).click();
    await page.locator('.planner-failure').waitFor();
    assert.match(await page.locator('.planner-failure').innerText(), /connection ended early/);
    await page.unroute('**/api/itinerary');
    const retry = page.waitForRequest(r => r.url().endsWith('/api/itinerary') && r.method() === 'POST');
    await page.getByRole('button', { name: 'Create my itinerary', exact: true }).click();
    assert.equal((await retry).postDataJSON().id, firstId);
    await page.locator('#result-heading').waitFor();
    const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('hellosrilanka-planner-v1')));
    const request = { id: crypto.randomUUID(), preferences: saved.itinerary.preferences };
    const [a, b] = await Promise.all([context.request.post(base + '/api/itinerary', { data: request }), context.request.post(base + '/api/itinerary', { data: request })]);
    const parse = async r => (await r.text()).trim().split('\n').map(s => JSON.parse(s)).find(e => e.result)?.result;
    const [ra, rb] = await Promise.all([parse(a), parse(b)]);
    assert.ok(ra && rb); assert.equal(ra.id, rb.id); assert.equal(ra.generatedAt, rb.generatedAt);
    const malformed = await context.request.post(base + '/api/itinerary', { data: { id: crypto.randomUUID(), preferences: { ...request.preferences, duration: 99 } } });
    assert.equal(malformed.status(), 400);
    // A long trip, narrow phone and blocked assets still yield readable paginated PNGs.
    const longResponse = await context.request.post(base + '/api/itinerary', { data: { id: crypto.randomUUID(), preferences: { ...request.preferences, duration: 21 } } });
    const longTrip = await parse(longResponse); assert.equal(longTrip.days.length, 21);
    const edge = await browser.newContext({ viewport: { width: 320, height: 740 }, acceptDownloads: true, reducedMotion: 'reduce' });
    await edge.route('**/*', route => /\.(woff2?|webp)(\?|$)/.test(route.request().url()) ? route.abort() : route.continue());
    await edge.addInitScript(({ trip, key }) => {
      localStorage.setItem(key, JSON.stringify({ preferences: trip.preferences, itinerary: trip, step: 4, screen: 'result', requestId: null }));
      window.exportDraws = [];
      const original = CanvasRenderingContext2D.prototype.fillText;
      CanvasRenderingContext2D.prototype.fillText = function(text, x, y, ...rest) {
        if (this.canvas.width === 1440) window.exportDraws.push({ text, x, y, width: this.measureText(text).width });
        return original.call(this, text, x, y, ...rest);
      };
    }, { trip: longTrip, key: 'hellosrilanka-planner-v1' });
    const narrow = await edge.newPage();
    await narrow.goto(base + '/plan'); await narrow.locator('#result-heading').waitFor();
    assert.ok(await narrow.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No 320px overflow');
    await narrow.getByRole('button', { name: 'Download as image', exact: true }).click();
    await narrow.locator('.export-previews figure').first().waitFor();
    assert.ok(await narrow.locator('.export-previews figure').count() >= 3, '21-day trip splits into multiple images');
    const draws = await narrow.evaluate(() => window.exportDraws);
    assert.ok(draws.some(d => d.text.startsWith('DAY 21')), 'Every day reaches the export');
    assert.ok(draws.every(d => d.width <= 1241 && d.y < 1920 && d.x >= 100), 'All text fits inside PNG bounds');
    await narrow.screenshot({ path: output + '/long-trip-320px.png', fullPage: true });
    await edge.close();
    // Device-storage failure is explained; keyboard-only controls still work.
    const noStorage = await browser.newContext({ viewport: { width: 390, height: 844 } });
    await noStorage.addInitScript(() => { Storage.prototype.setItem = () => { throw new Error('Storage denied'); }; });
    const local = await noStorage.newPage(); await local.goto(base + '/plan');
    await local.getByRole('checkbox', { name: 'Nature', exact: true }).waitFor();
    await local.getByRole('checkbox', { name: 'Nature', exact: true }).focus(); await local.keyboard.press('Space');
    await local.getByRole('button', { name: 'Find my rhythm', exact: true }).focus(); await local.keyboard.press('Enter');
    assert.ok(await local.getByRole('radio', { name: 'Relaxed', exact: true }).isVisible());
    assert.match(await local.locator('.storage-notice').innerText(), /storage is unavailable/);
    await noStorage.close();
    // Old drafts migrate to the correct new chapter without losing preferences.
    const legacy = await browser.newContext({ viewport: { width: 320, height: 740 } });
    await legacy.addInitScript(prefs => localStorage.setItem('hellosrilanka-planner-v1', JSON.stringify({ preferences: prefs, step: 1, screen: 'form', requestId: null })), request.preferences);
    const legacyPage = await legacy.newPage(); await legacyPage.goto(base + '/plan');
    await legacyPage.getByRole('button', { name: 'Set my budget', exact: true }).waitFor();
    assert.equal(await legacyPage.getByLabel('How many days?').inputValue(), String(request.preferences.duration));
    for (const name of ['Set my budget', 'Find my comforts', 'See my journey']) {
      assert.ok(await legacyPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No 320px chapter overflow');
      await legacyPage.getByRole('button', { name, exact: true }).click();
    }
    await legacyPage.getByRole('button', { name: 'Edit your moments & rhythm', exact: true }).click();
    assert.ok(await legacyPage.getByRole('checkbox', { name: 'Nature', exact: true }).isChecked());
    assert.ok(await legacyPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No 320px moments overflow');
    await legacyPage.screenshot({ path: output + '/moments-320px.png', fullPage: true });
    await legacy.close();
    assert.deepEqual(errors, []);
    console.log('PASS: visual discovery, responsive postcard, rhythm previews, old-draft migration, direct review edits, complete flow, validation, refresh, expansion, no maps, desktop/mobile, PNG dimensions, disconnected-stream retry, concurrent request deduplication, invalid API input, 21-day pagination, 320px layout, blocked fonts/images, export clipping checks, unavailable storage and keyboard controls.');
    console.log('Artifacts: ' + output);
  } catch (error) { await page.screenshot({ path: output + '/failure.png', fullPage: true }); console.error(await page.locator('main').innerText()); throw error; }
  finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
