import type { LandmarkSpec } from './landmarks';

export const destinationCategories = ['All places', 'Culture', 'Hill country', 'Wildlife', 'Coast', 'Nature'] as const;
export type DestinationCategory = Exclude<typeof destinationCategories[number], 'All places'>;
export type Destination = {
  id: string;
  artwork: LandmarkSpec;
  name: string;
  region: string;
  lat: number;
  lng: number;
  category: DestinationCategory;
  description: string;
  tags: string;
  image?: string;
  featured?: boolean;
};

// Map-level coordinates and source details are documented in SOURCES.md.
export const airport = { name: 'Bandaranaike International Airport', lat: 7.1808, lng: 79.8841 };

export const destinations: Destination[] = [
  { id: 'jaffna', artwork: { image: "Jaffna.png", importance: 'primary' }, name: 'Jaffna', region: 'Northern Province', lat: 9.66845, lng: 80.00742, category: 'Culture', description: 'Palmyra-lined roads, colourful temples and a rhythm all its own, at the island’s northern edge.', tags: 'Temples · Food · Northern shores', featured: true },
  { id: 'anuradhapura', artwork: { image: "Anuradhapura.png", importance: 'primary' }, name: 'Anuradhapura', region: 'North Central Province', lat: 8.31223, lng: 80.41306, category: 'Culture', description: 'White stupas rise above an ancient city where sacred groves and quiet paths invite you to slow down.', tags: 'Sacred cities · Heritage · Cycling' },
  { id: 'wilpattu', artwork: { image: "Wilpattu.png", importance: 'secondary', tablet: true }, name: 'Wilpattu National Park', region: 'Northwestern wilderness', lat: 8.4106, lng: 80.051, category: 'Wildlife', description: 'A quieter wilderness of natural lakes, forest tracks and wildlife glimpsed between the trees.', tags: 'Natural lakes · Safari · Forest' },
  { id: 'trincomalee', artwork: { image: "Trincomalee.png", importance: 'primary' }, name: 'Trincomalee', region: 'Eastern Province', lat: 8.5778, lng: 81.2289, category: 'Coast', description: 'A deep-blue harbour, cliffside temples and long stretches of sand on the eastern coast.', tags: 'Ocean · Temples · Slow mornings', featured: true },
  { id: 'sigiriya', artwork: { image: "Seegiriya.png", importance: 'primary' }, name: 'Sigiriya', region: 'Central Province', lat: 7.957, lng: 80.7603, category: 'Culture', description: 'An ancient rock fortress rising dramatically above the central plains. Take the climb; stay for the view.', tags: 'Heritage · Rock fortress · Wide horizons', image: 'sigiriya', featured: true },
  { id: 'dambulla', artwork: { image: "Dambulla.png", importance: 'secondary' }, name: 'Dambulla', region: 'Central Province', lat: 7.86, lng: 80.65167, category: 'Culture', description: 'Cave temples hold centuries of painted stories, high above the green heart of the island.', tags: 'Cave temples · Art · Heritage' },
  { id: 'minneriya', artwork: { image: "Minneriya.png", importance: 'secondary' }, name: 'Minneriya National Park', region: 'North Central Province', lat: 8.0308, lng: 80.8808, category: 'Wildlife', description: 'An ancient reservoir meets open grassland and forest, in a landscape shaped by water and wild elephants.', tags: 'Elephants · Wetlands · Safari' },
  { id: 'polonnaruwa', artwork: { image: "Polonnaruwa.png", importance: 'secondary', tablet: true }, name: 'Polonnaruwa', region: 'North Central Province', lat: 7.93965, lng: 81.00274, category: 'Culture', description: 'Cycle between stone Buddhas, royal ruins and shady avenues in this former island capital.', tags: 'Ancient cities · Cycling · Sculpture' },
  { id: 'pasikuda', artwork: { image: "Pasikuda.png", importance: 'secondary', tablet: true }, name: 'Pasikuda', region: 'Eastern Province', lat: 7.92351, lng: 81.56628, category: 'Coast', description: 'A broad sweep of pale sand and gentle blue water, made for unhurried days beside the sea.', tags: 'Beach · Quiet days · East coast' },
  { id: 'knuckles', artwork: { image: "Knuckels.png", importance: 'secondary', tablet: true }, name: 'Knuckles Mountain Range', region: 'Central Province', lat: 7.466, lng: 80.732, category: 'Nature', description: 'Folded ridgelines, misty trails and hidden valleys reward a little curiosity in the highlands.', tags: 'Hiking · Cloud forest · Mountain air' },
  { id: 'kandy', artwork: { image: "Kandy.png", importance: 'primary' }, name: 'Kandy', region: 'Central Province', lat: 7.2906, lng: 80.6336, category: 'Culture', description: 'A lakeside city wrapped in hills, with market mornings, sacred traditions and winding streets.', tags: 'Culture · Lake walks · Hill country', featured: true },
  { id: 'temple-of-the-tooth', artwork: { image: "Temple of tooth.png", importance: 'secondary' }, name: 'Temple of the Tooth', region: 'Kandy · Central Province', lat: 7.2936, lng: 80.6413, category: 'Culture', description: 'Beside Kandy Lake, the sacred temple remains a living centre of Buddhist devotion and island heritage.', tags: 'Sacred spaces · Heritage · Kandy' },
  { id: 'pinnawala', artwork: { image: "Pinnawala.png", importance: 'secondary', scale: .9 }, name: 'Pinnawala', region: 'Sabaragamuwa Province', lat: 7.3098, lng: 80.4014, category: 'Wildlife', description: 'A riverside village in the green foothills, closely associated with Sri Lanka’s elephants.', tags: 'Elephants · Riverside · Foothills' },
  { id: 'negombo', artwork: { image: "Negombo.png", importance: 'primary' }, name: 'Negombo', region: 'Western Province', lat: 7.2083, lng: 79.8358, category: 'Coast', description: 'Fishing boats, lagoon light and a first taste of the coast, a short journey from the airport.', tags: 'Lagoon · Fishing boats · First light', image: 'negombo-sunset' },
  { id: 'colombo', artwork: { image: "Colombo.png", importance: 'primary' }, name: 'Colombo', region: 'Western Province', lat: 6.93548, lng: 79.84868, category: 'Culture', description: 'Markets, galleries and oceanfront evenings. An island capital best discovered one neighbourhood at a time.', tags: 'Markets · Food · City life', image: 'market-life', featured: true },
  { id: 'kitulgala', artwork: { image: "Kitulgala.png", importance: 'primary' }, name: 'Kitulgala', region: 'Sabaragamuwa Province', lat: 6.9966, lng: 80.4068, category: 'Nature', description: 'The Kelani River threads through lush forest, with white-water adventures and quieter riverside moments.', tags: 'Rafting · Rainforest · River trails' },
  { id: 'adams-peak', artwork: { image: "Adam's peak.png", importance: 'secondary' }, name: 'Adam’s Peak / Sri Pada', region: 'Central highlands', lat: 6.8088, lng: 80.4972, category: 'Hill country', description: 'A sacred summit above the clouds, reached by a pilgrim path and remembered long after the descent.', tags: 'Pilgrimage · Mountain trails · Sunrise' },
  { id: 'nuwara-eliya', artwork: { image: "Nuwaraeliya.png", importance: 'primary' }, name: 'Nuwara Eliya', region: 'Central Province', lat: 6.97078, lng: 80.78286, category: 'Hill country', description: 'Cool mornings, tea gardens and soft mountain light. A different pace, high above the tropical coast.', tags: 'Tea country · Cool air · Gardens', image: 'nuwara-tea-country' },
  { id: 'horton-plains', artwork: { image: "Hortan Plains.png", importance: 'secondary' }, name: 'Horton Plains', region: 'Central Province', lat: 6.8031, lng: 80.7979, category: 'Nature', description: 'Open grasslands and cloud forest lead to dramatic escarpments in the island’s high country.', tags: 'Walking · Cloud forest · Big views' },
  { id: 'ella', artwork: { image: "Ella.png", importance: 'primary' }, name: 'Ella', region: 'Uva Province', lat: 6.87427, lng: 81.05342, category: 'Hill country', description: 'Follow the railway into green hills, then wander towards waterfalls, tea slopes and wide-open views.', tags: 'Train journeys · Trails · Tea country', image: 'train-person', featured: true },
  { id: 'haputale', artwork: { image: "Haputale.png", importance: 'secondary' }, name: 'Haputale', region: 'Uva Province', lat: 6.76566, lng: 80.95104, category: 'Hill country', description: 'A town perched on a ridge, where tea fields fall away into a seemingly endless green horizon.', tags: 'Tea estates · Ridge walks · Mist', image: 'nuwara-tea-pickers' },
  { id: 'arugam-bay', artwork: { image: "Arugambay.png", importance: 'primary' }, name: 'Arugam Bay', region: 'Eastern Province', lat: 6.8589, lng: 81.8304, category: 'Coast', description: 'Easy mornings, fishing boats and the pull of the next wave on the sun-warmed eastern coast.', tags: 'Surf · Beach life · East coast', image: 'arugam-fishing-boats', featured: true },
  { id: 'bentota', artwork: { image: "Bentota.png", importance: 'secondary' }, name: 'Bentota', region: 'Southern Province', lat: 6.42598, lng: 79.99575, category: 'Coast', description: 'Where river and ocean meet: golden beaches, quiet gardens and time spent beside the water.', tags: 'River · Gardens · Golden sand' },
  { id: 'sinharaja', artwork: { image: "Sinharaja Rain Forest.png", importance: 'secondary', tablet: true }, name: 'Sinharaja Rainforest', region: 'Southwestern rainforest', lat: 6.3897, lng: 80.5015, category: 'Nature', description: 'Step into a living canopy of giant trees, birdsong and intricate green detail.', tags: 'Rainforest · Birdlife · Walking' },
  { id: 'udawalawe', artwork: { image: "Udawalawe.png", importance: 'primary' }, name: 'Udawalawe National Park', region: 'Southern interior', lat: 6.51591, lng: 80.85388, category: 'Wildlife', description: 'Open plains and reservoir shores offer a window into the world of Sri Lanka’s wild elephants.', tags: 'Elephants · Safari · Open country', image: 'elephants-udawalawe' },
  { id: 'yala', artwork: { image: "Yala.png", importance: 'primary' }, name: 'Yala National Park', region: 'Southeastern wilderness', lat: 6.4, lng: 81.48333, category: 'Wildlife', description: 'Dry forest, lagoons and untamed coastline. A landscape full of small discoveries and wild possibility.', tags: 'Wildlife · Safari · Coastal wilderness', featured: true },
  { id: 'hikkaduwa', artwork: { image: "Hikkaduwa.png", importance: 'secondary' }, name: 'Hikkaduwa', region: 'Southern Province', lat: 6.1407, lng: 80.1012, category: 'Coast', description: 'A lively stretch of southern coast, with surf breaks, reef life and salt in the air.', tags: 'Surf · Reefs · Seaside days' },
  { id: 'galle', artwork: { image: "Galle.png", importance: 'primary' }, name: 'Galle', region: 'Southern Province', lat: 6.0461, lng: 80.2103, category: 'Culture', description: 'A southern port city where everyday island life meets centuries of maritime history.', tags: 'Coastal culture · Markets · Heritage', image: 'galle-lighthouse', featured: true },
  { id: 'galle-fort', artwork: { image: "Galle.png", importance: 'secondary' }, name: 'Galle Fort', region: 'Galle · Southern Province', lat: 6.026, lng: 80.217, category: 'Culture', description: 'Walk the ramparts, turn into a quiet lane and linger as the evening light settles over the ocean.', tags: 'Fort walls · Architecture · Sunset', image: 'galle-lighthouse' },
  { id: 'unawatuna', artwork: { importance: 'secondary' }, name: 'Unawatuna', region: 'Southern Province', lat: 6.0212, lng: 80.2503, category: 'Coast', description: 'A sheltered southern bay framed by palms, with beach cafés and little paths worth following.', tags: 'Beach · Sheltered bays · Palms' },
  { id: 'weligama', artwork: { image: "Weligama.png", importance: 'secondary' }, name: 'Weligama', region: 'Southern Province', lat: 5.97501, lng: 80.42968, category: 'Coast', description: 'A wide sandy bay, slow breakfasts and the simple pleasure of finding your feet on a surfboard.', tags: 'Surf · Sandy bays · Slow mornings' },
  { id: 'mirissa', artwork: { image: "Mirissa.png", importance: 'primary' }, name: 'Mirissa', region: 'Southern Province', lat: 5.95245, lng: 80.45667, category: 'Coast', description: 'Palm-fringed headlands, little coves and ocean views that ask you to stay a little longer.', tags: 'Ocean · Coves · Southern coast' },
  { id: 'hiriketiya', artwork: { image: "Hirikatiya.png", importance: 'secondary' }, name: 'Hiriketiya', region: 'Southern Province', lat: 5.963, lng: 80.706, category: 'Coast', description: 'A small horseshoe bay with a surf-side rhythm. One more swim, one more coffee, one more day.', tags: 'Surf · Small bays · Barefoot days', image: 'surf-hiriketiya' },
];
